texts_ko = {
    "summary_title": "예측 결과 요약",
    "model": "모델",
    "prediction": "회복 판단",
    "probability": "회복 확률",
    "accuracy": "예측 정확도",
    "예측 결과 요약": "예측 결과 요약",
    "모델": "모델",
    "회복 판단": "회복 판단",
    "회복 확률": "회복 확률",
    "예측 정확도": "예측 정확도",
    "회복": "회복",
    "님의 예측 결과는 다음과 같습니다.": "님의 예측 결과는 다음과 같습니다.",
    "{model} 기준 : 회복 확률 {p}%, 예측정확도 {a}%.": "{model} 기준 : 회복 확률 {p}%, 예측정확도 {a}%.",
    "변수 중요도": "변수 중요도",
    "전체 변수 중요도 보기": "전체 변수 중요도 보기",
    "조정가능한 변수 중요도 보기": "조정가능한 변수 중요도 보기",
    "변수중요도 기반 환자 수치 확인": "변수중요도 기반 환자 수치 확인",
    "병원 선택": "병원 선택",
    "전체 병원": "전체 병원",
    "기본 정보 입력": "기본 정보 입력",
    "PTA 검사": "PTA 검사",
    "의료 정보": "의료 정보",
    "혈액 검사": "혈액 검사",
    "진단 및 병력": "진단 및 병력",
    "예측 결과 보기": "예측 결과 보기",
    "비회복": "비회복",
    "원주세브란스기독병원": "원주세브란스기독병원",
    "신촌-강남세브란스병원": "신촌-강남세브란스병원",
    "한림대학교 강남성심병원": "한림대학교 강남성심병원",
    "제주대학병원": "제주대학병원",
    "독일하겐병원": "독일하겐병원",
    "생년월일": "생년월일",
    "성별": "성별",
    "이름": "이름",
    "병원코드 (HSPTCD)": "병원코드 (HSPTCD)",
    "측면 (Side)": "측면 (Side)",
    "HL_duration (일)": "HL_duration (일)",
    "스테로이드 치료": "스테로이드 치료",
    "IT_dexa 치료": "IT_dexa 치료",
    "고압산소 치료": "고압산소 치료",
    "여부": "여부",
    "기타 병력" : "기타 병력",
    "예측 진행 중..." : "예측 진행 중...",
    "기준" : "기준",
    "정상범위" : "정상범위",
    "기준 수치" : "기준 수치",
    "수치" : "수치",
    "환자수치" : "환자 수치",
    "조정가능 변수" : "조정가능 변수",
    "결과 저장" : "결과 저장",
    "저장" : "저장",
    "낮아": "낮아",
    "높아": "높아",
    "증가시켜야 함.": "증가시켜야 함.",
    "감소시켜야 함.": "감소시켜야 함.",
    "수치는": "수치는",
    "정상범위인": "정상범위인",
    "보다": "보다",
    "로" : "로"
    }

texts_en_us = {
    "summary_title": "Summary of prediction results",
    "model": "Model",
    "prediction": "Recovery decision",
    "probability": "Recovery probability",
    "accuracy": "Prediction accuracy",
    "예측 결과 요약": "Summary of prediction results",
    "모델": "Model",
    "회복 판단": "Recovery decision",
    "회복 확률": "Recovery probability",
    "예측 정확도": "Prediction accuracy",
    "회복": "Recovered",
    "님의 예측 결과는 다음과 같습니다.": "The prediction result for is as follows.",
    "{model} 기준 : 회복 확률 {p}%, 예측정확도 {a}%.": "Based on {model}: recovery probability {p}%, prediction accuracy {a}%.",
    "변수 중요도": "Variable importance",
    "전체 변수 중요도 보기": "View all variable importance",
    "조정가능한 변수 중요도 보기": "View modifiable variable importance",
    "변수중요도 기반 환자 수치 확인": "Check patient values based on variable importance",
    "병원 선택": "Select hospital",
    "전체 병원": "All hospitals",
    "기본 정보 입력": "Enter basic information",
    "PTA 검사": "PTA test",
    "의료 정보": "Medical information",
    "혈액 검사": "Blood test",
    "진단 및 병력": "Diagnosis and history",
    "예측 결과 보기": "See prediction results",
    "비회복": "Not recovered",
    "원주세브란스기독병원": "Wonju Severance Christian Hospital",
    "신촌-강남세브란스병원": "Shinchon-Gangnam Severance Hospital",
    "한림대학교 강남성심병원": "Hallym University Kangnam Sacred Heart Hospital",
    "제주대학병원": "Jeju National University Hospital",
    "독일하겐병원": "University of Hagen Hospital",
    "생년월일": "Date of Birth",
    "성별": "Sex",
    "이름": "Name",
    "병원코드 (HSPTCD)": "Hospital code",
    "측면 (Side)": "Affected Ear",
    "HL_duration (일)": "HL Duration (days)",
    "스테로이드 치료": "Steroid treatment",
    "IT_dexa 치료": "IT_dexa treatment",
    "고압산소 치료": "Hyperbaric oxygen therapy",
    "여부" : "Whether",
    "기타 병력" : "Other medical history",
    "예측 진행 중..." : "Prediction in progress",
    "기준" : "Criteria",
    "정상범위" : "Normal range",
    "기준 수치" : "criterion value",
    "수치" : "value",
    "환자수치" : "patient figures",
    "조정가능 변수" : "Modifiable variables",
    "결과 저장" : "Save Results",
    "저장" : "Save",
    "낮아": "low",
    "높아": "high",
    "증가시켜야 함.": "should be increased.",
    "감소시켜야 함.": "should be decreased.",
    "수치는": "is",
    "정상범위인": "Normal range",
    "보다": "than",
    "로" : ","
}


texts_ja = {
    "summary_title": "予測結果の要約",
    "model": "モデル",
    "prediction": "回復の判断",
    "probability": "回復の確率",
    "accuracy": "予測精度",
    "예측 결과 요약": "予測結果の要約",
    "모델": "モデル",
    "회복 판단": "回復の判断",
    "회복 확률": "回復の確率",
    "예측 정확도": "予測精度",
    "회복": "回復",
    "님의 예측 결과는 다음과 같습니다.": "さんの予測結果は以下の通りです。",
    "{model} 기준 : 회복 확률 {p}%, 예측정확도 {a}%.": "{model} に基づいて、回復の確率は {p}%、予測精度は {a}% です。",
    "변수 중요도": "変数の重要度",
    "전체 변수 중요도 보기": "全ての変数の重要度を見る",
    "조정가능한 변수 중요도 보기": "調整可能な変数の重要度を見る",
    "변수중요도 기반 환자 수치 확인": "変数の重要度に基づく患者の値を確認",
    "병원 선택": "病院を選択",
    "전체 병원": "全ての病院",
    "기본 정보 입력": "基本情報の入力",
    "PTA 검사": "PTA検査",
    "의료 정보": "医療情報",
    "혈액 검사": "血液検査",
    "진단 및 병력": "診断と病歴",
    "예측 결과 보기": "予測結果を見る",
    "비회복": "非回復",
    "원주세브란스기독병원": "原州セブランスキリスト病院",
    "신촌-강남세브란스병원": "新村・江南セブランス病院",
    "한림대학교 강남성심병원": "翰林大学江南聖心病院",
    "제주대학병원": "済州大学病院",
    "독일하겐병원": "ドイツ・ハーゲン病院",
    "생년월일": "生年月日",
    "성별": "性別",
    "이름": "名前",
    "병원코드 (HSPTCD)": "病院コード（HSPTCD）",
    "측면 (Side)": "影響を受けた耳",
    "HL_duration (일)": "難聴期間（日）",
    "스테로이드 치료": "ステロイド治療",
    "IT_dexa 치료": "IT_dexa治療",
    "고압산소 치료": "高圧酸素治療",
    "여부": "有無",
    "기타 병력": "その他の病歴",
    "예측 진행 중...": "予測中...",
    "기준": "基準",
    "정상범위": "正常範囲",
    "기준 수치": "基準値",
    "수치": "数値",
    "환자수치": "患者の数値",
    "조정가능 변수": "調整可能な変数",
    "결과 저장": "結果を保存",
    "저장": "保存",
    "낮아": "低い",
    "높아": "高い",
    "증가시켜야 함.": "増加させる必要があります。",
    "감소시켜야 함.": "減少させる必要があります。",
    "수치는": "数値は",
    "정상범위인": "正常範囲の",
    "보다": "より",
    "로": "、"
}

texts_zh = {
    "summary_title": "预测结果摘要",
    "model": "模型",
    "prediction": "恢复判断",
    "probability": "恢复概率",
    "accuracy": "预测准确率",
    "예측 결과 요약": "预测结果摘要",
    "모델": "模型",
    "회복 판단": "恢复判断",
    "회복 확률": "恢复概率",
    "예측 정확도": "预测准确率",
    "회복": "恢复",
    "님의 예측 결과는 다음과 같습니다.": "您的预测结果如下：",
    "{model} 기준 : 회복 확률 {p}%, 예측정확도 {a}%.": "基于 {model}：恢复概率为 {p}% ，预测准确率为 {a}%。",
    "변수 중요도": "变量重要性",
    "전체 변수 중요도 보기": "查看所有变量的重要性",
    "조정가능한 변수 중요도 보기": "查看可调变量的重要性",
    "변수중요도 기반 환자 수치 확인": "根据变量重要性查看患者数值",
    "병원 선택": "选择医院",
    "전체 병원": "所有医院",
    "기본 정보 입력": "输入基本信息",
    "PTA 검사": "PTA 检查",
    "의료 정보": "医疗信息",
    "혈액 검사": "血液检查",
    "진단 및 병력": "诊断和病史",
    "예측 결과 보기": "查看预测结果",
    "비회복": "未恢复",
    "원주세브란스기독병원": "原州世福兰斯基督教医院",
    "신촌-강남세브란스병원": "新村-江南世福兰斯医院",
    "한림대학교 강남성심병원": "翰林大学江南圣心医院",
    "제주대학병원": "济州大学医院",
    "독일하겐병원": "德国哈根医院",
    "생년월일": "出生日期",
    "성별": "性别",
    "이름": "姓名",
    "병원코드 (HSPTCD)": "医院代码 (HSPTCD)",
    "측면 (Side)": "受影响的耳朵",
    "HL_duration (일)": "听力丧失时长（日）",
    "스테로이드 치료": "类固醇治疗",
    "IT_dexa 치료": "IT_dexa 治疗",
    "고압산소 치료": "高压氧治疗",
    "여부": "是否",
    "기타 병력": "其他病史",
    "예측 진행 중...": "预测进行中...",
    "기준": "标准",
    "정상범위": "正常范围",
    "기준 수치": "参考值",
    "수치": "数值",
    "환자수치": "患者数值",
    "조정가능 변수": "可调变量",
    "결과 저장": "保存结果",
    "저장": "保存",
    "낮아": "低",
    "높아": "高",
    "증가시켜야 함.": "需要提高。",
    "감소시켜야 함.": "需要降低。",
    "수치는": "数值为",
    "정상범위인": "正常范围为",
    "보다": "比",
    "로": "，"
}

texts_es = {
    "summary_title": "Resumen de los resultados de la predicción",
    "model": "Modelo",
    "prediction": "Decisión de recuperación",
    "probability": "Probabilidad de recuperación",
    "accuracy": "Precisión de la predicción",
    "예측 결과 요약": "Resumen de los resultados de la predicción",
    "모델": "Modelo",
    "회복 판단": "Decisión de recuperación",
    "회복 확률": "Probabilidad de recuperación",
    "예측 정확도": "Precisión de la predicción",
    "회복": "Recuperado",
    "님의 예측 결과는 다음과 같습니다.": "El resultado de su predicción es el siguiente:",
    "{model} 기준 : 회복 확률 {p}%, 예측정확도 {a}%.": "Según {model}: probabilidad de recuperación {p}%, precisión {a}%.",
    "변수 중요도": "Importancia de la variable",
    "전체 변수 중요도 보기": "Ver importancia de todas las variables",
    "조정가능한 변수 중요도 보기": "Ver importancia de variables modificables",
    "변수중요도 기반 환자 수치 확인": "Ver valores del paciente según importancia de la variable",
    "병원 선택": "Seleccionar hospital",
    "전체 병원": "Todos los hospitales",
    "기본 정보 입력": "Ingresar información básica",
    "PTA 검사": "Prueba PTA",
    "의료 정보": "Información médica",
    "혈액 검사": "Análisis de sangre",
    "진단 및 병력": "Diagnóstico e historial",
    "예측 결과 보기": "Ver resultados de la predicción",
    "비회복": "No recuperado",
    "원주세브란스기독병원": "Hospital Cristiano Severance de Wonju",
    "신촌-강남세브란스병원": "Hospital Severance Shinchon-Gangnam",
    "한림대학교 강남성심병원": "Hospital Kangnam Sacred Heart de la Universidad Hallym",
    "제주대학병원": "Hospital Universitario de Jeju",
    "독일하겐병원": "Hospital de Hagen (Alemania)",
    "생년월일": "Fecha de nacimiento",
    "성별": "Sexo",
    "이름": "Nombre",
    "병원코드 (HSPTCD)": "Código del hospital (HSPTCD)",
    "측면 (Side)": "Oído afectado",
    "HL_duration (일)": "Duración de pérdida auditiva (días)",
    "스테로이드 치료": "Tratamiento con esteroides",
    "IT_dexa 치료": "Tratamiento IT_dexa",
    "고압산소 치료": "Terapia de oxígeno hiperbárico",
    "여부": "Sí / No",
    "기타 병력": "Otros antecedentes médicos",
    "예측 진행 중...": "Predicción en curso...",
    "기준": "Criterio",
    "정상범위": "Rango normal",
    "기준 수치": "Valor de referencia",
    "수치": "Valor",
    "환자수치": "Valor del paciente",
    "조정가능 변수": "Variables modificables",
    "결과 저장": "Guardar resultado",
    "저장": "Guardar",
    "낮아": "Bajo",
    "높아": "Alto",
    "증가시켜야 함.": "Debe aumentarse.",
    "감소시켜야 함.": "Debe reducirse.",
    "수치는": "El valor",
    "정상범위인": "dentro del rango normal",
    "보다": "que",
    "로": ","
}

texts_de = {
    "summary_title": "Zusammenfassung der Vorhersageergebnisse",
    "model": "Modell",
    "prediction": "Genesungsentscheidung",
    "probability": "Genesungswahrscheinlichkeit",
    "accuracy": "Vorhersagegenauigkeit",
    "예측 결과 요약": "Zusammenfassung der Vorhersageergebnisse",
    "모델": "Modell",
    "회복 판단": "Genesungsentscheidung",
    "회복 확률": "Genesungswahrscheinlichkeit",
    "예측 정확도": "Vorhersagegenauigkeit",
    "회복": "Genesen",
    "님의 예측 결과는 다음과 같습니다.": "Ihr Vorhersageergebnis lautet wie folgt:",
    "{model} 기준 : 회복 확률 {p}%, 예측정확도 {a}%.": "Basierend auf {model}: Genesungswahrscheinlichkeit {p}%, Vorhersagegenauigkeit {a}%",
    "변수 중요도": "Variablenbedeutung",
    "전체 변수 중요도 보기": "Alle Variablenbedeutungen anzeigen",
    "조정가능한 변수 중요도 보기": "Anpassbare Variablen anzeigen",
    "변수중요도 기반 환자 수치 확인": "Patientenwerte basierend auf Variablenbedeutung anzeigen",
    "병원 선택": "Krankenhaus auswählen",
    "전체 병원": "Alle Krankenhäuser",
    "기본 정보 입력": "Grundinformationen eingeben",
    "PTA 검사": "PTA-Test",
    "의료 정보": "Medizinische Informationen",
    "혈액 검사": "Blutuntersuchung",
    "진단 및 병력": "Diagnose und Vorgeschichte",
    "예측 결과 보기": "Vorhersageergebnisse anzeigen",
    "비회복": "Nicht genesen",
    "원주세브란스기독병원": "Wonju Severance Christliches Krankenhaus",
    "신촌-강남세브란스병원": "Shinchon-Gangnam Severance Krankenhaus",
    "한림대학교 강남성심병원": "Kangnam Sacred Heart Krankenhaus der Hallym Universität",
    "제주대학병원": "Universitätskrankenhaus Jeju",
    "독일하겐병원": "Krankenhaus Hagen (Deutschland)",
    "생년월일": "Geburtsdatum",
    "성별": "Geschlecht",
    "이름": "Name",
    "병원코드 (HSPTCD)": "Krankenhauscode (HSPTCD)",
    "측면 (Side)": "Betroffenes Ohr",
    "HL_duration (일)": "Hörverlustdauer (Tage)",
    "스테로이드 치료": "Steroidbehandlung",
    "IT_dexa 치료": "IT_dexa-Behandlung",
    "고압산소 치료": "Hyperbare Sauerstofftherapie",
    "여부": "Ja / Nein",
    "기타 병력": "Weitere Krankengeschichte",
    "예측 진행 중...": "Vorhersage läuft...",
    "기준": "Kriterium",
    "정상범위": "Normalbereich",
    "기준 수치": "Referenzwert",
    "수치": "Wert",
    "환자수치": "Patientenwert",
    "조정가능 변수": "Anpassbare Variablen",
    "결과 저장": "Ergebnis speichern",
    "저장": "Speichern",
    "낮아": "Niedrig",
    "높아": "Hoch",
    "증가시켜야 함.": "Muss erhöht werden.",
    "감소시켜야 함.": "Muss reduziert werden.",
    "수치는": "Der Wert ist",
    "정상범위인": "im Normalbereich",
    "보다": "als",
    "로": ","
}

texts_hi = {
    "summary_title": "पूर्वानुमान परिणामों का सारांश",
    "model": "मॉडल",
    "prediction": "रिकवरी निर्णय",
    "probability": "रिकवरी की संभावना",
    "accuracy": "पूर्वानुमान सटीकता",
    "예측 결과 요약": "पूर्वानुमान परिणामों का सारांश",
    "모델": "मॉडल",
    "회복 판단": "रिकवरी निर्णय",
    "회복 확률": "रिकवरी की संभावना",
    "예측 정확도": "पूर्वानुमान सटीकता",
    "회복": "ठीक हुआ",
    "님의 예측 결과는 다음과 같습니다.": "आपका पूर्वानुमान परिणाम इस प्रकार है:",
    "{model} 기준 : 회복 확률 {p}%, 예측정확도 {a}%.": "{model} के आधार पर: रिकवरी की संभावना {p}%, पूर्वानुमान सटीकता {a}%",
    "변수 중요도": "चर का महत्व",
    "전체 변수 중요도 보기": "सभी चर के महत्व देखें",
    "조정가능한 변수 중요도 보기": "समायोज्य चर के महत्व देखें",
    "변수중요도 기반 환자 수치 확인": "चर के महत्व के आधार पर रोगी मान देखें",
    "병원 선택": "अस्पताल चुनें",
    "전체 병원": "सभी अस्पताल",
    "기본 정보 입력": "मूल जानकारी दर्ज करें",
    "PTA 검사": "PTA परीक्षण",
    "의료 정보": "चिकित्सा जानकारी",
    "혈액 검사": "रक्त परीक्षण",
    "진단 및 병력": "निदान और चिकित्सा इतिहास",
    "예측 결과 보기": "पूर्वानुमान परिणाम देखें",
    "비회복": "रिकवरी नहीं हुई",
    "원주세브란스기독병원": "वोनजु सेवरेंस क्रिश्चियन अस्पताल",
    "신촌-강남세브란스병원": "शिनचोन-गंगनम सेवरेंस अस्पताल",
    "한림대학교 강남성심병원": "हैलीम यूनिवर्सिटी कांगनम सोंगशिम अस्पताल",
    "제주대학병원": "जेजू विश्वविद्यालय अस्पताल",
    "독일하겐병원": "जर्मनी हागेन अस्पताल",
    "생년월일": "जन्म तिथि",
    "성별": "लिंग",
    "이름": "नाम",
    "병원코드 (HSPTCD)": "अस्पताल कोड (HSPTCD)",
    "측면 (Side)": "प्रभावित कान",
    "HL_duration (일)": "सुनवाई हानि की अवधि (दिनों में)",
    "스테로이드 치료": "स्टेरॉइड उपचार",
    "IT_dexa 치료": "IT_dexa उपचार",
    "고압산소 치료": "हाइपरबैरिक ऑक्सीजन थेरेपी",
    "여부": "हां / नहीं",
    "기타 병력": "अन्य चिकित्सा इतिहास",
    "예측 진행 중...": "पूर्वानुमान जारी है...",
    "기준": "मानदंड",
    "정상범위": "सामान्य सीमा",
    "기준 수치": "मानक मूल्य",
    "수치": "मान",
    "환자수치": "रोगी का मान",
    "조정가능 변수": "समायोज्य चर",
    "결과 저장": "परिणाम सहेजें",
    "저장": "सहेजें",
    "낮아": "कम",
    "높아": "अधिक",
    "증가시켜야 함.": "इसे बढ़ाना होगा।",
    "감소시켜야 함.": "इसे घटाना होगा।",
    "수치는": "मान है",
    "정상범위인": "सामान्य सीमा",
    "보다": "से",
    "로": ","
}

texts_ar = {
    "summary_title": "ملخص نتائج التنبؤ",
    "model": "النموذج",
    "prediction": "قرار الشفاء",
    "probability": "احتمالية الشفاء",
    "accuracy": "دقة التنبؤ",
    "예측 결과 요약": "ملخص نتائج التنبؤ",
    "모델": "النموذج",
    "회복 판단": "قرار الشفاء",
    "회복 확률": "احتمالية الشفاء",
    "예측 정확도": "دقة التنبؤ",
    "회복": "متعافٍ",
    "님의 예측 결과는 다음과 같습니다.": "نتيجة التنبؤ الخاصة بك كما يلي:",
    "{model} 기준 : 회복 확률 {p}%, 예측정확도 {a}%.": "بناءً على {model}: احتمالية الشفاء {p}%، دقة التنبؤ {a}%",
    "변수 중요도": "أهمية المتغيرات",
    "전체 변수 중요도 보기": "عرض جميع المتغيرات",
    "조정가능한 변수 중요도 보기": "عرض المتغيرات القابلة للتعديل",
    "변수중요도 기반 환자 수치 확인": "عرض قيم المريض بناءً على أهمية المتغير",
    "병원 선택": "اختر المستشفى",
    "전체 병원": "جميع المستشفيات",
    "기본 정보 입력": "أدخل المعلومات الأساسية",
    "PTA 검사": "اختبار PTA",
    "의료 정보": "المعلومات الطبية",
    "혈액 검사": "تحليل الدم",
    "진단 및 병력": "التشخيص والتاريخ الطبي",
    "예측 결과 보기": "عرض نتائج التنبؤ",
    "비회복": "غير متعافٍ",
    "원주세브란스기독병원": "مستشفى وونجو سيفيرانس المسيحي",
    "신촌-강남세브란스병원": "مستشفى سيفيرانس شينتشون-غانغنام",
    "한림대학교 강남성심병원": "مستشفى كانغنام سونغشيم بجامعة هاليم",
    "제주대학병원": "مستشفى جامعة جيجو",
    "독일하겐병원": "مستشفى هاغن الألماني",
    "생년월일": "تاريخ الميلاد",
    "성별": "الجنس",
    "이름": "الاسم",
    "병원코드 (HSPTCD)": "رمز المستشفى (HSPTCD)",
    "측면 (Side)": "الأذن المتأثرة",
    "HL_duration (일)": "مدة فقدان السمع (أيام)",
    "스테로이드 치료": "علاج الستيرويد",
    "IT_dexa 치료": "علاج IT_dexa",
    "고압산소 치료": "علاج الأوكسجين عالي الضغط",
    "여부": "نعم / لا",
    "기타 병력": "تاريخ طبي آخر",
    "예측 진행 중...": "جاري التنبؤ...",
    "기준": "المعيار",
    "정상범위": "النطاق الطبيعي",
    "기준 수치": "القيمة المرجعية",
    "수치": "القيمة",
    "환자수치": "قيمة المريض",
    "조정가능 변수": "المتغيرات القابلة للتعديل",
    "결과 저장": "حفظ النتيجة",
    "저장": "حفظ",
    "낮아": "منخفض",
    "높아": "مرتفع",
    "증가시켜야 함.": "يجب زيادته.",
    "감소시켜야 함.": "يجب تقليله.",
    "수치는": "القيمة هي",
    "정상범위인": "النطاق الطبيعي",
    "보다": "أكثر من",
    "로": "،"
}
